package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	version "github.com/rbaliyan/go-version"
)

// defaultDateFormat is the default date command format string, producing RFC 3339 output.
const defaultDateFormat = "%Y-%m-%dT%H:%M:%SZ"

const usage = `go-version - Generate and manage version files

Usage:
  go-version <command> [options]

Commands:
  file        Generate a .version file from git or manual input
  ldflags     Generate go build command with -ldflags for version injection
  show        Show version information from git
  version     Show go-version CLI version

Run 'go-version <command> -h' for more information on a command.
`

const fileUsage = `Generate a .version file

Usage:
  go-version file [options]

Options:
  -o, --output       Output file path (default: .version)
  -v, --version      Version string (default: from git describe)
  -t, --timestamp    Build timestamp (default: current time)
      --timeformat   Timestamp format for date command (default: "%%Y-%%m-%%dT%%H:%%M:%%SZ")

Examples:
  go-version file                                                     # Generate from git
  go-version file -o build/.version                                   # Custom output path
  go-version file -v 1.2.3                                            # Manual version
  go-version file --timeformat "%%a %%b %%d %%H:%%M:%%S %%Z %%Y"     # UnixDate format
`

const showUsage = `Show version information from git

Usage:
  go-version show
`

const ldflagsUsage = `Generate -ldflags value for version injection

Usage:
  go-version ldflags [options]

Options:
  -p, --package      Package path (default: github.com/rbaliyan/go-version)
  -v, --version      Version string (default: from git describe)
  -t, --timestamp    Include build timestamp in ldflags (default: false)
      --timeformat   Timestamp format for date command (default: "%%Y-%%m-%%dT%%H:%%M:%%SZ")
      --shell        Output shell command with $() substitutions (default)
      --static       Output static values instead of shell substitutions

Examples:
  go build -ldflags="$(go-version ldflags)" ./cmd/myapp                        # Without timestamp
  go build -ldflags="$(go-version ldflags -t)" ./cmd/myapp                     # With timestamp (RFC 3339)
  go build -ldflags="$(go-version ldflags -t --timeformat '%%Y-%%m-%%d')" ./cmd/myapp
  go build -ldflags="$(go-version ldflags --static)" ./cmd/myapp               # Static values for CI
`

func main() {
	if len(os.Args) < 2 {
		fmt.Print(usage)
		os.Exit(0)
	}

	switch os.Args[1] {
	case "file":
		cmdFile(os.Args[2:])
	case "ldflags":
		cmdLdflags(os.Args[2:])
	case "show":
		cmdShow(os.Args[2:])
	case "version", "-v", "--version":
		cmdVersion()
	case "-h", "--help", "help":
		fmt.Print(usage)
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\n\n", os.Args[1])
		fmt.Print(usage)
		os.Exit(1)
	}
}

func cmdFile(args []string) {
	fs := flag.NewFlagSet("file", flag.ExitOnError)
	fs.Usage = func() { _, _ = os.Stdout.WriteString(fileUsage) }

	var output, ver, timestamp, timeformat string
	fs.StringVar(&output, "o", ".version", "Output file path")
	fs.StringVar(&output, "output", ".version", "Output file path")
	fs.StringVar(&ver, "v", "", "Version string")
	fs.StringVar(&ver, "version", "", "Version string")
	fs.StringVar(&timestamp, "t", "", "Build timestamp")
	fs.StringVar(&timestamp, "timestamp", "", "Build timestamp")
	fs.StringVar(&timeformat, "timeformat", defaultDateFormat, "Timestamp format (date command format)")

	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing flags: %v\n", err)
		os.Exit(1)
	}

	// Gather git info
	commit := gitCommand("rev-parse", "HEAD")
	branch := gitCommand("rev-parse", "--abbrev-ref", "HEAD")
	repo := gitCommand("remote", "get-url", "origin")

	// Use git describe for version if not provided
	if ver == "" {
		ver = gitCommand("describe", "--tags", "--always")
	}

	// Use current time if timestamp not provided
	if timestamp == "" {
		timestamp = dateCommand(timeformat)
	}

	// Build file content
	var sb strings.Builder
	sb.WriteString("# Generated by go-version\n")
	if ver != "" {
		sb.WriteString(fmt.Sprintf("VERSION=%s\n", ver))
	}
	if commit != "" {
		sb.WriteString(fmt.Sprintf("GIT_COMMIT=%s\n", commit))
	}
	if branch != "" {
		sb.WriteString(fmt.Sprintf("GIT_BRANCH=%s\n", branch))
	}
	if repo != "" {
		sb.WriteString(fmt.Sprintf("GIT_REPO=%s\n", repo))
	}
	sb.WriteString(fmt.Sprintf("BUILD_TIMESTAMP=%s\n", timestamp))

	// Write to file
	if err := os.WriteFile(output, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", output)
}

func cmdShow(args []string) {
	fs := flag.NewFlagSet("show", flag.ExitOnError)
	fs.Usage = func() { fmt.Print(showUsage) }
	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing flags: %v\n", err)
		os.Exit(1)
	}

	commit := gitCommand("rev-parse", "HEAD")
	branch := gitCommand("rev-parse", "--abbrev-ref", "HEAD")
	repo := gitCommand("remote", "get-url", "origin")
	version := gitCommand("describe", "--tags", "--always")

	fmt.Printf("Version:  %s\n", valueOrNA(version))
	fmt.Printf("Commit:   %s\n", valueOrNA(commit))
	fmt.Printf("Branch:   %s\n", valueOrNA(branch))
	fmt.Printf("Repo:     %s\n", valueOrNA(repo))
}

func gitCommand(args ...string) string {
	cmd := exec.Command("git", args...)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func dateCommand(format string) string {
	out, err := exec.Command("date", "-u", "+"+format).Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func valueOrNA(s string) string {
	if s == "" {
		return "N/A"
	}
	return s
}

func cmdVersion() {
	version.SetAppInfo("go-version", "Generate and manage version files for Go projects")
	v := version.Get()
	g := version.Git()
	b := version.Build()

	fmt.Printf("go-version %s\n", v.Raw)
	if g.Commit != "" {
		fmt.Printf("  commit:  %s\n", g.Commit)
	}
	if g.Branch != "" {
		fmt.Printf("  branch:  %s\n", g.Branch)
	}
	if !b.Timestamp.IsZero() {
		fmt.Printf("  built:   %s\n", b.Timestamp.Format(time.RFC3339))
	}
}

func cmdLdflags(args []string) {
	fs := flag.NewFlagSet("ldflags", flag.ExitOnError)
	fs.Usage = func() { _, _ = os.Stdout.WriteString(ldflagsUsage) }

	var pkg, ver, timeformat string
	var static, timestamp bool
	fs.StringVar(&pkg, "p", "", "Package path")
	fs.StringVar(&pkg, "package", "", "Package path")
	fs.StringVar(&ver, "v", "", "Version string")
	fs.StringVar(&ver, "version", "", "Version string")
	fs.BoolVar(&static, "static", false, "Output static values")
	fs.BoolVar(&timestamp, "t", false, "Include build timestamp")
	fs.BoolVar(&timestamp, "timestamp", false, "Include build timestamp")
	fs.StringVar(&timeformat, "timeformat", defaultDateFormat, "Timestamp format (date command format)")

	if err := fs.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing flags: %v\n", err)
		os.Exit(1)
	}

	// Use go-version package path by default
	if pkg == "" {
		pkg = "github.com/rbaliyan/go-version"
	}

	var flags []string

	if static {
		// Static values - resolve everything now
		commit := gitCommand("rev-parse", "HEAD")
		branch := gitCommand("rev-parse", "--abbrev-ref", "HEAD")
		repo := gitCommand("remote", "get-url", "origin")

		if ver == "" {
			ver = gitCommand("describe", "--tags", "--always")
		}

		if ver != "" {
			flags = append(flags, fmt.Sprintf("-X '%s.VersionInfo=%s'", pkg, ver))
		}
		if commit != "" {
			flags = append(flags, fmt.Sprintf("-X '%s.GitCommit=%s'", pkg, commit))
		}
		if branch != "" {
			flags = append(flags, fmt.Sprintf("-X '%s.GitBranch=%s'", pkg, branch))
		}
		if repo != "" {
			flags = append(flags, fmt.Sprintf("-X '%s.GitRepo=%s'", pkg, repo))
		}
		if timestamp {
			ts := dateCommand(timeformat)
			flags = append(flags, fmt.Sprintf("-X '%s.BuildTimestamp=%s'", pkg, ts))
		}
	} else {
		// Shell substitutions for use in scripts/Makefiles
		if ver != "" {
			flags = append(flags, fmt.Sprintf("-X '%s.VersionInfo=%s'", pkg, ver))
		} else {
			flags = append(flags, fmt.Sprintf("-X '%s.VersionInfo=$(git describe --tags --always)'", pkg))
		}
		flags = append(flags, fmt.Sprintf("-X '%s.GitCommit=$(git rev-parse HEAD)'", pkg))
		flags = append(flags, fmt.Sprintf("-X '%s.GitBranch=$(git rev-parse --abbrev-ref HEAD)'", pkg))
		flags = append(flags, fmt.Sprintf("-X '%s.GitRepo=$(git remote get-url origin)'", pkg))
		if timestamp {
			flags = append(flags, fmt.Sprintf("-X '%s.BuildTimestamp=$(date -u \"+%s\")'", pkg, timeformat))
		}
	}

	fmt.Println(strings.Join(flags, " "))
}
